using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyHealthManager : MonoBehaviour {
    public int enemyHealth;
    public GameObject deathEffect;
    public int currencyOnKill;
	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
		if(enemyHealth <= 0)
        {
            Instantiate(deathEffect, transform.position, transform.rotation);
            currencyOnKill = Random.Range(1, 100);
            VoidEssenceManager.AddCurrencyOnKill(currencyOnKill);
            Destroy(gameObject);
        }
	}
    public void dealDamage(int damageToDeal)
    {
        enemyHealth -= damageToDeal;
    }
}
